### PR TITLE
Add acceptance test for Kerberos master

### PR DESCRIPTION
**Pull request by martialblog**
Hi, 
I finally found some time to write tests for the Kerberos Master. While doing that, I found some missing variables in the manifests. See commits. 

Build:
https://travis-ci.org/martialblog/puppet-module-kerberos/builds/170763754

Let me know if there are any issues with the branch.

Cheers

### CODE REVIEW

**Comment by martialblog** [comment]
Ok, seems like the Build isn't that stable yet. Sometimes the container runs into a timeout (Command exceeded timeout). 

I'll have a look at it...

**Comment by martialblog** [comment]
Locally the beaker test runs 10 out of 10. In Travis CI however sometimes we get a timeout... I couldn't figure out why. 

I disabled the catch_failure option for the beaker Puppet run. The serverspec assertions run fine however and should cover it.

**Comment by martialblog** [comment]
I you decide to merge this, could you update the Module Version?  :shipit:

Didn't know if it's cool if I do it...

**Comment by edgester** [comment]
Version 0.3.1 released, Thanks!

**Pull request merged**
