### PR TITLE
Silence almost all lint warnings

### PR DESCRIPTION
**Pull request by michaelweiser**
Hi Jason,

sorry for not helping with the travis stuff - I was away. I've had a look at the changes and started packaging for Debian. Here are some changes I made in the process.

Only one line-length and one params class warning remains. The latter is
only relevant for compatibility with Puppet < 2.6.2, which to be honest
I don't care about.

### CODE REVIEW

**Comment by michaelweiser** [comment]
Um, I see travis is still (again?) failing. I had a look but don't have the slightest what's going on there.

**Comment by edgester** [comment]
I fixed travis on my master branch. Please rebase and see if travis is happier.

**Comment by michaelweiser** [comment]
Looks good. Thanks!

**Comment by michaelweiser** [comment]
BTW: The Debian package is here https://anonscm.debian.org/cgit/pkg-puppet/puppet-module-edgester-kerberos.git. It's unclear if and when it will turn up in actual Debian though since I'm not an uploader and build binary packages for my projects locally only but it's there, can be built and works.

**Comment by edgester** [comment]
Thanks. I doubt that I'll use the debian package, but it sounds cool.

**Pull request merged**
